#
# Environment values
#
## Your timezone, https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# TZ=Europe/Stockholm
## UNIX PUID and PGID, find with: id $USER
# PUID=1000
# PGID=1000
## The directory where data and configuration will be stored.
# ROOT=/data/0/htpc
#

version: "2.4"
services:
  #  vpn:
  #    container_name: vpn
  #    image: dperson/openvpn-client:latest
  #    cap_add:
  #      - net_admin # required to modify network interfaces
  #    restart: unless-stopped
  #    volumes:
  #      - /dev/net:/dev/net:z # tun device
  #      - ${ROOT}/config/vpn:/vpn # OpenVPN configuration
  #    security_opt:
  #      - label:disable
  #    ports:
  #      - 8112:8112 # port for deluge web UI to be reachable from local network
  #    command: '-f "" -r 192.168.1.0/24' # enable firewall and route local network traffic

  deluge:
    container_name: deluge
    hostname: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    # network_mode: service:vpn # run on the vpn network
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/config/deluge:/config # config files
    #  ports:
      # - 8112:8112
      # - 58846:58846

  jackett:
    container_name: jackett
    hostname: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    # network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files
    ports:
      - 9117:9117
      
  sabnzbd:
    image: linuxserver/sabnzbd
    hostname: sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/sabnzbd:/config # config files
      - ${ROOT}/downloads/complete:/downloads # downloads folder
      - ${ROOT}/downloads/incomplete:/incomplete-downloads # incomplete downloads folder
    ports:
      - 38080:8080
      - 9090:9090
    restart: unless-stopped
    
  nzbhydra:
    container_name: nzbhydra
    hostname: nzbhydra
    image: linuxserver/nzbhydra2
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/nzbhydra:/config # config files
      - ${ROOT}/downloads:/downloads # downloads folder
    ports:
      - 5076:5076
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    hostname: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    # network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/complete/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder
    ports:
      - 8989:8989

  radarr:
    container_name: radarr
    hostname: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    # network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder
    ports:
     - 7878:7878
     
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      # - DOCKER_MODS=linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - ${ROOT}/config/lazylibrarian:/config # config files
      - ${ROOT}/downloads:/downloads # download folder
      - ${ROOT}/complete/books:/books
    ports:
      - 5299:5299
    restart: unless-stopped

  plex-server:
    container_name: plex-server
    hostname: plex-server
    image: plexinc/pms-docker:latest
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/plex/db:/config # plex database
      - ${ROOT}/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}/complete:/data # media library
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

  bazarr:
    container_name: bazarr
    hostname: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    # network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/config/bazarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/complete/tv:/tv # tv shows folder
    ports:
      - 6767:6767

  ombi:
    container_name: ombi
    hostname: ombi
    image: linuxserver/ombi
    restart: unless-stopped
    # network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      # - BASE_URL=/ombi #optional
    volumes:
      - ${ROOT}/config/ombi:/config
    ports:
      - 3579:3579
      
  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr
    restart: unless-stopped
    # network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - fpm=true # Used to enable php to use the socket rather than TCP, often increases performance.
    volumes:
      - ${ROOT}/config/organizr:/config
    ports:
      - 9983:80

  unpackerr:
    container_name: unpackerr
    hostname: unpackerr
    image: golift/unpackerr
    restart: unless-stopped
    # network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # download folder
      - ${ROOT}/config/unpackerr:/config # config folder
      - ${ROOT}/config/unpackerr/unpackerr.conf:/etc/unpackerr/unpackerr.conf # config file
