#!/bin/sh
chsh -s $(which zsh)
sudo mkdir /var/cache/pacman/custom -m 777
sudo pacman-mirrors --api --set-branch testing
sudo pacman-mirrors --fasttrack 5 && sudo pacman -Syyu
#pamac upgrade -a

sudo usermod -a -G video $USER # Needed for light
sudo usermod -a -G input $USER # Needed for libinput-gestures/fusuma

mkdir ~/.ssh/sockets

# Shared folder
sudo mkdir /home/sharedFolder/
sudo chgrp users /home/sharedFolder/
sudo chmod 770 /home/sharedFolder/
sudo chmod +s /home/sharedFolder/

# Storing backups of all installed packages
mkdir /home/sharedFolder/package_lists/


