#!/bin/bash

if read proto cookie && [ -n "$DISPLAY" ]; then
        if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
                # X11UseLocalhost=yes
                echo add unix:`echo $DISPLAY |
                    cut -c11-` $proto $cookie
        else
                # X11UseLocalhost=no
                echo add $DISPLAY $proto $cookie
        fi | xauth -q -
fi

# Applications/environment variables
[[ -f $HOME/.config/zsh/exports ]] && . $HOME/.config/zsh/exports


# SSH Agent forwarding with tmux
if [ ! -S ~/.ssh/ssh_auth_sock ] && [ -S "$SSH_AUTH_SOCK" ]; then
	ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi

if [[ $HOST == "htpc" ]]; then
  export DISPLAY=:0
fi

tmux start-server

