swipe:
  3:
    left:
      command: 'xdotool key ctrl+Page_Up'
      threshold: 0.7
    right:
      threshold: 0.7
      command: 'xdotool key ctrl+Page_Down'
    up:
      command: 'xdotool key Home'
    down:
      command: 'xdotool key End'
  4:
    left:
      command: 'xdotool key XF86AudioLowerVolume'
      interval: 0.02
      keypress:
        LEFTSHIFT:
          command: 'change_brightness subtract 30'
          interval: 0.1

    right:
      command: 'xdotool key XF86AudioRaiseVolume'
      interval: 0.02
      keypress:
        LEFTSHIFT:
          command: 'change_brightness add 30'
          interval: 0.1

    up:
      command: 'xdotool key XF86AudioMute'
    down:
      command: 'change_brightness toggle'

pinch:
  2:
    in:
      command: 'xdotool key ctrl+equal'
    out:
      command: 'xdotool key ctrl+minus'
  4:
    in:
      command: ''
    out:
      command: ''

threshold:
  swipe: 0.5
  pinch: 0.5

interval:
  swipe: 1
  pinch: 1

plugin:
  inputs:
    libinput_command_input:
      show-keycodes: true
