# Ensure plugins are installed:
# gem install fusuma-plugin-keypress
# gem install fusuma-plugin-tap
# gem install fusuma-plugin-appmatcher

swipe:
  3:
    left:
      command: 'xdotool key ctrl+Page_Up'
      threshold: 1.5
    right:
      threshold: 1.5
      command: 'xdotool key ctrl+Page_Down'
    up:
      command: 'xdotool key Home'
    down:
      command: 'xdotool key End'
  4:
    left:
      update:
        command: 'xdotool key XF86AudioLowerVolume'
        interval: 0.1
        keypress:
          LEFTSHIFT:
            command: 'change_brightness dec'
            interval: 0.5

    right:
      update:
        command: 'xdotool key XF86AudioRaiseVolume'
        interval: 0.1
        keypress:
          LEFTSHIFT:
            command: 'change_brightness inc'
            interval: 0.5

    up:
      command: 'xdotool key XF86AudioMute'
    down:
      command: 'change_brightness toggle'

pinch:
  2:
    in:
      update:
        command: 'xdotool key ctrl+equal'
    out:
      update:
        command: 'xdotool key ctrl+minus'
  4:
    in:
      command: ''
    out:
      command: ''

---
context:
  application: firefox
tap:
  3:
    command: 'xdotool keydown ctrl click 1 keyup ctrl'
---

threshold:
  swipe: 0.5
  pinch: 0.5

interval:
  swipe: 1
  pinch: 1

plugin:
  inputs:
    libinput_command_input:
      show-keycodes: true
      # fusuma-plugin-tap
      enable-tap: true
      verbose: true
